name: Code formatting

on:
  pull_request:
    branches: [master, develop]

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: black
      run: black --check ./resample
    - name: flake8
      run: flake8 ./resample
    - name: isort
      run: isort . --check-only
    - name: mypy
      run: mypy ./resample
