name: Coverage

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.rst'
  push:
    branches:
      - master
      - develop
      - beta/*
    paths-ignore:
      - 'doc/**'
      - '*.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PIP_ONLY_BINARY: ":all:"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install -e .[test]
    - run: coverage run -m pytest
    - run: python -m pip uninstall --yes numba
    - run: coverage run --append -m pytest
    - uses: AndreMiras/coveralls-python-action@develop
