name: Coverage

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.rst'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PIP_ONLY_BINARY: ":all:"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install -e .[test]
    - run: coverage run -m pytest
    # needed by coveralls
    - run: python -m pip install toml
    - uses: AndreMiras/coveralls-python-action@develop
