name: Coverage

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.rst'
  push:
    branches:
      - master
      - develop
      - beta/*
    paths-ignore:
      - 'doc/**'
      - '*.rst'

env:
  PIP_ONLY_BINARY: ":all:"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - run: python -m pip install --upgrade pip
    # workaround to avoid having different numpy versions during build/test
    - run: python -m pip install wheel numpy setuptools setuptools_scm[toml]
    - run: python -m pip install pytest pytest-cov numba
    - run: python -m pip install --no-build-isolation -e .
    - run: coverage run -m pytest
    - run: python -m pip uninstall --yes numba
    - run: coverage run --append -m pytest
    - uses: AndreMiras/coveralls-python-action@develop
